import { Body, Container, Head, Heading, Hr, Html, Preview, Text } from "@react-email/components";
import type { Lead } from "@/lib/schemas/lead";
import type { AgentBrief } from "@/lib/schemas/agentBrief";
import { formatLine } from "@/lib/format/insuranceLine";

/**
 * Internal-only, gated behind AGENT_BRIEF_EMAIL (default off, see
 * notifyAgentBrief in lib/notifications/leadNotify.ts) -- never sent to the
 * customer. Mirrors RequestConfirmationEmail.tsx's inline-style structure,
 * but the contact block below is deliberately unredacted (phone/email/
 * state) since the reader is agency staff who already have the full Lead,
 * unlike redact.ts's model-facing input.
 */
export function AgentBriefEmail({ lead, brief }: { lead: Lead; brief: AgentBrief }) {
  const { content } = brief;

  return (
    <Html>
      <Head />
      <Preview>{content.headline}</Preview>
      <Body style={{ backgroundColor: "#f4f4f5", fontFamily: "Arial, sans-serif" }}>
        <Container style={{ backgroundColor: "#ffffff", padding: "32px", borderRadius: "8px", maxWidth: "560px" }}>
          <Heading style={{ fontSize: "20px", color: "#0f172a" }}>{content.headline}</Heading>
          <Text style={{ fontSize: "14px", color: "#475569", textTransform: "uppercase", fontWeight: "bold" }}>
            {content.urgency.tier} · {content.recommendedNextAction}
          </Text>
          {content.urgency.reasons.map((reason, i) => (
            <Text key={i} style={{ fontSize: "14px", color: "#1e293b", margin: "2px 0" }}>
              {reason}
            </Text>
          ))}

          <Text style={{ fontSize: "16px", color: "#1e293b" }}>{content.summary}</Text>

          <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
          <Text style={{ fontSize: "14px", color: "#1e293b" }}>
            {lead.contact.firstName} {lead.contact.lastName}
            <br />
            {lead.contact.phone ?? "no phone"} · {lead.contact.email ?? "no email"}
            <br />
            {lead.contact.state}
          </Text>

          {content.keyFacts.length > 0 && (
            <>
              <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
              <Heading as="h3" style={{ fontSize: "16px", color: "#0f172a" }}>
                Key facts
              </Heading>
              {content.keyFacts.map((fact, i) => (
                <Text key={i} style={{ fontSize: "14px", color: "#1e293b", margin: "4px 0" }}>
                  <strong>{fact.label}:</strong> {fact.value}
                  {fact.basis === "inferred" ? " (inferred)" : ""}
                </Text>
              ))}
            </>
          )}

          {content.missingFields.length > 0 && (
            <>
              <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
              <Heading as="h3" style={{ fontSize: "16px", color: "#0f172a" }}>
                Missing fields
              </Heading>
              <Text style={{ fontSize: "14px", color: "#1e293b" }}>{content.missingFields.join(", ")}</Text>
            </>
          )}

          {content.suggestedQuestions.length > 0 && (
            <>
              <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
              <Heading as="h3" style={{ fontSize: "16px", color: "#0f172a" }}>
                Suggested questions
              </Heading>
              {content.suggestedQuestions.map((question, i) => (
                <Text key={i} style={{ fontSize: "14px", color: "#1e293b", margin: "4px 0" }}>
                  • {question}
                </Text>
              ))}
            </>
          )}

          {content.riskFlags.length > 0 && (
            <>
              <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
              <Heading as="h3" style={{ fontSize: "16px", color: "#b91c1c" }}>
                Risk flags
              </Heading>
              {content.riskFlags.map((flag, i) => (
                <Text key={i} style={{ fontSize: "14px", color: "#b91c1c", margin: "4px 0" }}>
                  • {flag}
                </Text>
              ))}
            </>
          )}

          {content.crossSellCandidates.length > 0 && (
            <>
              <Hr style={{ borderColor: "#e2e8f0", margin: "16px 0" }} />
              <Heading as="h3" style={{ fontSize: "16px", color: "#0f172a" }}>
                Cross-sell
              </Heading>
              <Text style={{ fontSize: "14px", color: "#1e293b" }}>{content.crossSellCandidates.map(formatLine).join(", ")}</Text>
            </>
          )}

          <Hr style={{ borderColor: "#e2e8f0", margin: "24px 0" }} />
          <Text style={{ fontSize: "12px", color: "#64748b" }}>
            Generated by {brief.origin === "model" ? brief.model : "deterministic fallback"} · prompt {brief.promptVersion} ·
            internal use only, not customer-facing
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
