import type { AgentBriefContent } from "@/lib/schemas/agentBrief";
import { formatLine } from "@/lib/format/insuranceLine";

/**
 * Plain presentational renderer -- the single shared view for both the
 * claim-time instant snapshot (ClaimButton, no `meta`, never persisted) and
 * a persisted dashboard brief (FollowUpCard via ExpandableBriefSection,
 * `meta` given). No fetching, no client state.
 */
export function AgentBriefPanel({
  content,
  meta,
}: {
  content: AgentBriefContent;
  meta?: { origin: "model" | "fallback"; model: string | null; promptVersion: string };
}) {
  return (
    <div className="rounded-md border border-brand-200 bg-brand-50 p-3 text-xs">
      <p className="font-serif text-sm font-semibold text-brand-900">{content.headline}</p>
      <p className="mt-1 text-brand-600">
        <span className="font-semibold uppercase">{content.urgency.tier}</span> · {content.recommendedNextAction}
      </p>
      {content.urgency.reasons.length > 0 && (
        <ul className="mt-1 list-disc pl-4 text-brand-700">
          {content.urgency.reasons.map((reason, i) => (
            <li key={i}>{reason}</li>
          ))}
        </ul>
      )}

      <p className="mt-2 text-brand-800">{content.summary}</p>

      {content.keyFacts.length > 0 && (
        <div className="mt-2">
          <p className="font-semibold uppercase tracking-wide text-brand-500">Key facts</p>
          <dl className="mt-1 grid grid-cols-2 gap-x-3 gap-y-1 sm:grid-cols-3">
            {content.keyFacts.map((fact, i) => (
              <div key={i}>
                <dt className="text-brand-500">{fact.label}</dt>
                <dd className="text-brand-800">
                  {fact.value}
                  {fact.basis === "inferred" ? " (inferred)" : ""}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      )}

      {content.missingFields.length > 0 && (
        <p className="mt-2">
          <span className="font-semibold uppercase tracking-wide text-brand-500">Missing: </span>
          <span className="text-brand-700">{content.missingFields.join(", ")}</span>
        </p>
      )}

      {content.suggestedQuestions.length > 0 && (
        <div className="mt-2">
          <p className="font-semibold uppercase tracking-wide text-brand-500">Ask on the call</p>
          <ul className="mt-1 list-disc pl-4 text-brand-700">
            {content.suggestedQuestions.map((question, i) => (
              <li key={i}>{question}</li>
            ))}
          </ul>
        </div>
      )}

      {content.riskFlags.length > 0 && (
        <div className="mt-2">
          <p className="font-semibold uppercase tracking-wide text-red-600">Risk flags</p>
          <ul className="mt-1 list-disc pl-4 text-red-700">
            {content.riskFlags.map((flag, i) => (
              <li key={i}>{flag}</li>
            ))}
          </ul>
        </div>
      )}

      {content.crossSellCandidates.length > 0 && (
        <p className="mt-2">
          <span className="font-semibold uppercase tracking-wide text-brand-500">Cross-sell: </span>
          <span className="text-brand-700">{content.crossSellCandidates.map(formatLine).join(", ")}</span>
        </p>
      )}

      {meta && (
        <p className="mt-2 border-t border-brand-200 pt-2 text-brand-400">
          Generated by {meta.origin === "model" ? meta.model : "deterministic fallback"} · prompt {meta.promptVersion}
        </p>
      )}
    </div>
  );
}
